### ISSUE TITLE
Feature Request: Ability to scroll through images.

### ISSUE THREAD

**Issue by rtevans01** [yomotsu/GLSlideshow.js#10]
Hello. Every time I press a key, the screensaver ends. Is it possible to scroll through images using the keyboard? Also, would it be possible to be able to pause the slideshow by pressing the P button or open a directory path for an image by pressing E? The reason I ask is because I'm used to running [Random Photo Screensaver](https://github.com/marijnkampf/Random-Photo-Screensaver) on Windows which has these features. Thanks.

**Comment by yomotsu** [comment]
I think you are posting to a wrong place.
This lib is not the screensaver program, I think.
