### ISSUE TITLE
Please help me capturing

### ISSUE THREAD

**Issue by haiduong87** [yomotsu/GLSlideshow.js#11]
Hi @yomotsu,

Thanks for the lib.

Now I want to capture the slide show and save to webm (using MediaRecorder).
I've tried and could capture result, but the quality is not as expected.

Here's the code (copy from basic.html)

[basic2.zip](https://github.com/yomotsu/gl-slideshow/files/7261905/basic2.zip)

Please help me.

Thank you,
Duong Nguyen

**Comment by yomotsu** [comment]
Thanks for using the lib.
But sorry, App-level issues should be handled on your side...
Please ask your developer team.
