### ISSUE TITLE
Video playback and more

### ISSUE THREAD

**Issue by stamp** [yomotsu/GLSlideshow.js#2]
Hi!

I forked your awesome library and started adding some features. This is the first time I'm working with WebGL so its probably not the best code but it works :D 

Stuff that I got working is:
 - Video playback
 - Automatic ratio handling for video and images in crossZoom transition (have only altered that one yet)
 - Start slideshow without images (it only shows transparent pixels then)
 - Transition in to empty slide (by calling transition(-1)) 

My code is not great, its more of an experiment. But maybe you can have some use for it?

Anyway... Great work with your library and it have been fun to start playing around with WebGL.

// stamp

**Comment by yomotsu** [comment]
@stamp Thanks for your fork. sounds cool! I saw your repo and looks nice 😃
I wonder if you could send a pull request except build files.
