### ISSUE TITLE
Adding new GLSL transitions

### ISSUE THREAD

**Issue by genericandy** [yomotsu/GLSlideshow.js#3]
I am trying to add a new GLSL transition from https://gl-transitions.com/ and the format does not seem to match up. I'm rather new to GLSL in general so I am not sure what would need to happen to convert the format there to work with this package or how to fork this & make it work with their new formatting.

Any help would be appreciated.

**Comment by yomotsu** [comment]
@genericandy which shader did you grab?

**Comment by genericandy** [comment]
There were a few I was hoping to try. Links are below.
https://gl-transitions.com/editor/squareswire
https://gl-transitions.com/editor/Radial

**Comment by yomotsu** [comment]
This has been supported as [addShader](http://yomotsu.github.io/gl-slideshow/examples/shader.html).
Closing for now.
