### ISSUE TITLE
Adding different effects to each Image

### ISSUE THREAD

**Issue by siva123kumar** [yomotsu/GLSlideshow.js#7]
I am new to gl-transitions.May I know how to add different effects to each image like cross fade for 1st image,directional wipe for second and so on .Thank You

**Comment by yomotsu** [comment]
You could change the effect right after `transitionEnd` event for every slide.

see http://yomotsu.github.io/gl-slideshow/examples/apis.html to change the effect

**Comment by yomotsu** [comment]
I think it should be solved.

**Comment by siva123kumar** [comment]
Thank you for your response.It helped me a lot and solved my problem.Thank
You once again.
